# Generated by Django 5.1.7 on 2025-03-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area_plot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=50)),
                ('newcustomer', models.IntegerField()),
                ('oldcustomer', models.IntegerField()),
            ],
            options={
                'db_table': 'area_plot',
            },
        ),
        migrations.CreateModel(
            name='Bar_plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('revenue', models.IntegerField()),
            ],
            options={
                'db_table': 'bar_plot',
            },
        ),
        migrations.CreateModel(
            name='Box_plot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50)),
                ('mean', models.IntegerField()),
                ('q1', models.IntegerField()),
                ('median', models.IntegerField()),
                ('q2', models.IntegerField()),
                ('max', models.IntegerField()),
            ],
            options={
                'db_table': 'box_plot',
            },
        ),
        migrations.CreateModel(
            name='Heatmap_plot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=50)),
                ('january', models.IntegerField()),
                ('february', models.IntegerField()),
                ('march', models.IntegerField()),
                ('april', models.IntegerField()),
                ('may', models.IntegerField()),
            ],
            options={
                'db_table': 'heatmap_plot',
            },
        ),
        migrations.CreateModel(
            name='Histogram_plot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('agegroup', models.CharField(max_length=50)),
                ('customers', models.IntegerField()),
            ],
            options={
                'db_table': 'histogram_plot',
            },
        ),
        migrations.CreateModel(
            name='Line_plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('sales', models.IntegerField()),
            ],
            options={
                'db_table': 'line_plot',
            },
        ),
        migrations.CreateModel(
            name='Pie_plot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=50)),
                ('marketshare', models.IntegerField()),
            ],
            options={
                'db_table': 'pie_plot',
            },
        ),
        migrations.CreateModel(
            name='Radar_plot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('aspect', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'radar_plot',
            },
        ),
        migrations.CreateModel(
            name='Scatter_plot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hoursstudied', models.CharField(max_length=50)),
                ('examscore', models.IntegerField()),
            ],
            options={
                'db_table': 'scatter_plot',
            },
        ),
        migrations.CreateModel(
            name='StackedBar_plot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quater', models.CharField(max_length=50)),
                ('electronics', models.IntegerField()),
                ('furniture', models.IntegerField()),
                ('clothing', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'stackedbar_plot',
            },
        ),
    ]
